server:
  port: 8099

secure:
  ignored:
    urls: #安全路径白名单
      -/admin/public/user/login
      -admin/grow/queryGrow/**
      -/js/**
      -/css/**
      -/img/**
      -/**.html
      -/swagger-ui.html
      -/doc.html
