#todo 记得把这些配置信息补充了
##################端口##################
memory.server.port=8080
##################mysql配置##################
memory.mysql.ip=120.55.127.90
#memory.mysql.ip=172.18.0.2
memory.mysql.port=3306
memory.mysql.db=memory
memory.mysql.username=root
memory.mysql.password=weijie1229
##################redis配置##################
memory.redis.host=120.55.127.90
memory.redis.port=6379
memory.redis.password=123456
memory.redis.database=0


