server:
  port: 9999

spring:
  application:
    name: memory
  datasource:
    url: jdbc:mysql://${memory.mysql.ip}:${memory.mysql.port}/${memory.mysql.db}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ${memory.mysql.username}
    password: ${memory.mysql.password}
  redis:
    # Redis服务器地址
    host: ${memory.redis.host}
      # 使用的数据库索引，默认是0
    database: ${memory.redis.database}
    # Redis服务器端口号
    port: ${memory.redis.port}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    #格式化全局时间字段
    date-format: yyyy-MM-dd HH:mm:ss
    #指定时间区域类型
    time-zone: GMT+8
logging:
  level:
    root: info
    com.gnahz: debug
# mybatis-plus相关配置
mybatis-plus:
  #配置日志
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
#    是否开启驼峰命名（true为开启）
    map-underscore-to-camel-case: true

aliyun:
  oss:
    endpoint: ${oss.endpoint} # oss对外服务的访问域名
    accessKeyId: ${oss.access-key} # 访问身份验证中用到用户标识
    accessKeySecret: ${oss.secret-key} # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: ${oss.bucketName} # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://localhost:9999/admin/aliyun/oss/callback  # 文件上传成功后的回调地址
    dir:
      prefix: gnahz/yi # 上传文件夹路径前缀

#secure:
#  ignored:
#    urls: #安全路径白名单
#      - /admin/**

jwt:
  secret: ${memory.jwt.secret}  #服务端私钥（一定不能泄露）
  expiration: 86400   #过期时间 60*60*24  =一天
  tokenHead: Bearer #jwt规范  #告诉客户端jwt令牌开头需要加的一个字符串
  tokenHeader: Authorization #告诉客户端你要在请求头里面传什么参数名字

redis:
  #memory
  database: memory
  expire:
    common: 86400 # 24小时
  key:
    user: 'ums:member:'
    prefix:
      orderId: 'portal:orderId:'
secure:
  ignored:
    urls: #安全路径白名单
      -/admin/public/user/login
      -admin/grow/queryGrow/**
      -/js/**
      -/css/**
      -/img/**
      -/**.html
      -/swagger-ui.html
      -/doc.html

email:
  smtp:
    host: smtp.qq.com
    email: 2162417277@qq.com
    name: 邮件提醒系统
    password: gcfoamlcdqirecgj
    port: 25
