server:
  port: 9999

spring:
  application:
    name: memory
  datasource:
    url: jdbc:mysql://localhost:3306/memory?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: hsp
logging:
  level:
    root: info
    com.gnahz: debug
# mybatis-plus相关配置
mybatis-plus:
  #配置日志
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
#    是否开启驼峰命名（true为开启）
    map-underscore-to-camel-case: true

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI5t5wMe9KqzE5vhZVhGia # 访问身份验证中用到用户标识
    accessKeySecret: 16QS2DxrLpeZyBl9NOjUIBlZKupm7H # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: gnahz-yi # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    #callback:  # 文件上传成功后的回调地址
    dir:
      prefix: gnahz/yi # 上传文件夹路径前缀
