#todo 记得把这些配置信息补充了
##################jwt##################
memory.jwt.secret=memory_admin
##################OSS配置##################
oss.endpoint=oss-cn-hangzhou.aliyuncs.com
oss.access-key=LTAI5t5wMe9KqzE5vhZVhGia
oss.secret-key=16QS2DxrLpeZyBl9NOjUIBlZKupm7H
oss.bucketName=gnahz-yi



