server:
  port: 9999

spring:
  application:
    name: memory
  datasource:
    url: jdbc:mysql://localhost:3306/memory?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: hsp
logging:
  level:
    root: info
    com.gnahz: debug
# mybatis-plus相关配置
mybatis-plus:
  #配置日志
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
#    是否开启驼峰命名（true为开启）
    map-underscore-to-camel-case: true
